[env:NM-CYD-C5]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
; board = nm-cyd-c5
board = esp32-c5-devkitc-1
framework = arduino

monitor_filters = esp32_exception_decoder
monitor_speed = 115200
monitor_rts     = 0
monitor_dtr     = 0
upload_speed = 460800

; === Partitions (16MB chip) ===
board_build.partitions = partitions.csv

; === Build flags relevant to your project ===
build_flags =
    ; USB serial (required for NM-CYD-C5)
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -D CORE_DEBUG_LEVEL=3
    
    ; ST7789 display driver
    -DST7789_DRIVER=1
    
    ; Default rotation (landscape)
    -DROTATION=3
    
    ; Display dimensions
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    
    ; TFT pin definitions (used by GFX library wrappers)
    -DTFT_BL=25
    -DTFT_DC=24
    -DTFT_RST=-1           ; Hardware reset, no GPIO needed
    -DTFT_MISO=2
    -DTFT_MOSI=7
    -DTFT_SCLK=6
    -DTFT_CS=23
    -DTOUCH_CS=1
    
    ; Touch calibration values (from Official)
    -DCYD28_TouchR_CAL_XMIN=185
    -DCYD28_TouchR_CAL_XMAX=3700
    -DCYD28_TouchR_CAL_YMIN=250
    -DCYD28_TouchR_CAL_YMAX=3800
    
    ; PSRAM support
    ; -DBOARD_HAS_PSRAM
    
    ; Board identifier
    -DNM_CYD_C5

; === Library dependencies ===
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
    ; marian-craciunescu/ESP32Ping @ ^1.7 ; removed — vendored in lib/ESP32Ping-Patched (log_d patch)
    paulstoffregen/XPT2046_Touchscreen
    ; Wire
    ; SD
    ; FS
    ; ESP32Async/ESPAsyncWebServer
    ; bblanchon/ArduinoJson @ ^7.0.4
